### ISSUE TITLE
Laravel 9 compatibility

### ISSUE THREAD

**Issue by gbradley** [conedevelopment/i18n#32]
Hi there, it would be great for this package to support Laravel 9 :)

I think the only change beyond bumping the Composer requirements would be due to Laravel 9 moving the `resources/lang` folder to the top level of the project. I'm happy to submit a PR for this if that would help, just not 100% certain on how to best test the change.

**Comment by iamgergo** [comment]
Hi there!

I would gladly accept a PR for this, thank you! I'll merge the shift PR as well soon!

Thank you!

**Comment by iamgergo** [comment]
@gbradley What do you think, should we drop the support for versions under Laravel 8?

**Comment by gbradley** [comment]
@iamgergo Probably does make sense to do that and bump the major version up; if you like I'll update the PR.

**Comment by iamgergo** [comment]
Okay, thank you! I merged the shift PR as well.

**Comment by iamgergo** [comment]
So I updated the dependecies so the versions as well. Soon I'll make a release. Thanks!
